export const GLOSSARY: Record<string, string> = {
  SKU: 'Stock Keeping Unit — a unique code that identifies a specific product variant.',
  DC: 'Distribution Centre — a warehouse from which products are dispatched to stores.',
  PO: 'Purchase Order — a formal request to a supplier to deliver a specific quantity of a product.',
  ETA: 'Estimated Time of Arrival — the expected date a shipment will reach the distribution centre.',
  MAPE: 'Mean Absolute Percentage Error — measures forecast accuracy; lower is better. Under 10% is excellent, 10–20% is acceptable, above 20% needs attention.',
  ATP: 'Available to Promise — the quantity available to commit to new orders: On-Hand + In-Transit − Reserved.',
  OTD: 'On-Time Delivery rate — the percentage of supplier shipments that arrived on or before the agreed date.',
  P10: '10th percentile forecast — a cautious estimate; demand has only a 10% chance of falling below this level.',
  P50: '50th percentile forecast (median) — the midpoint estimate; demand is equally likely to be above or below this level.',
  P90: '90th percentile forecast — an optimistic estimate; demand has only a 10% chance of exceeding this level.',
  ON_HAND: 'Units currently in stock at the distribution centre, available for dispatch.',
  IN_TRANSIT: 'Units ordered from a supplier that are on their way to the distribution centre, not yet received.',
  RESERVED: 'Units already allocated to pending orders and not available for new commitments.',
  REORDER_POINT: 'The stock level that triggers a replenishment order — when stock falls below this point, a new order should be placed.',
  SAFETY_STOCK: 'A buffer of extra inventory held to guard against unexpected demand spikes or supplier delays.',
  LOW_STOCK: 'Alert raised when inventory falls below the reorder point and a replenishment order is needed.',
  OVERSTOCK: 'Alert raised when inventory significantly exceeds expected demand, risking excess holding costs.',
  OTD_RATE: "On-Time Delivery rate — percentage of this supplier's orders that arrived on or before the committed date.",
  PO_SLA: 'PO Acknowledgement SLA — the percentage of orders the supplier confirmed within the agreed timeframe.',
  LEAD_TIME_VARIANCE: 'How many days earlier (negative) or later (positive) the supplier delivered compared to the agreed lead time.',
  FILL_RATE: 'The percentage of ordered quantity actually delivered by the supplier in full.',
  OPEN_EXCEPTIONS: 'Unresolved delivery problems — items that arrived damaged, short, or outside agreed terms.',
  REPLENISHMENT_CYCLE_TIME: 'Average number of days from a purchase order being raised to the shipment being dispatched.',
  FORECAST_COVERAGE: 'The percentage of active SKUs that have a valid demand forecast available for planning.',
  PROMO_UPLIFT: 'A percentage increase applied to the base forecast to account for expected demand lift from a promotion.',
  DATA_FRESHNESS: 'The timestamp of the most recent data refresh — indicates how current the figures on screen are.',
  STOCKOUT_RISK: 'The likelihood that a product will run out of stock before the next replenishment arrives.',
  VERSION: 'A change counter used to prevent two people from overwriting each other\'s updates. The system will warn you if the order was changed since you opened it.',
}
