spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartretail?currentSchema=replenishment
    username: smartretail_admin
    password: local_dev_password
  cloud:
    aws:
      parameterstore:
        enabled: false
      secretsmanager:
        enabled: false
      sqs:
        enabled: false

smartretail:
  eventbridge:
    bus-name: mock-local
