spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

smartretail:
  sqs:
    pos-events-queue-url: http://localhost:4566/000000000000/smartretail-pos-events-local
