spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartretail?currentSchema=sales
    username: smartretail_admin
    password: local_dev_password
  cloud:
    aws:
      parameterstore:
        enabled: false
      secretsmanager:
        enabled: false

smartretail:
  eventbridge:
    bus-name: mock-local
  mock:
    ims-url: http://localhost:8081
