spring:
  application:
    name: ims
  datasource:
    url: jdbc:postgresql://${RDS_PROXY_ENDPOINT:localhost}:5432/smartretail?currentSchema=${DB_SCHEMA:inventory}
    username: ${DB_USERNAME:smartretail_admin}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: SmartRetail-IMS-Pool
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

server:
  port: 8081
  shutdown: graceful

logging:
  config: classpath:logback-spring.xml
