spring:
  datasource:
    url: jdbc:postgresql://${RDS_PROXY_ENDPOINT}:5432/smartretail?currentSchema=sales
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

smartretail:
  firehose:
    delivery-stream: ${FIREHOSE_DELIVERY_STREAM_NAME}
  eventbridge:
    bus-name: ${EVENTBRIDGE_BUS_NAME}
