spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartretail?currentSchema=sales
    username: smartretail_admin
    password: local_dev_password

smartretail:
  localstack:
    endpoint: http://localhost:4566
  firehose:
    access-key: local-dev-key
  eventbridge:
    bus-name: smartretail-events-local
