AWSTemplateFormatVersion: '2010-09-09'
Description: SmartRetail Identity Stack

Parameters:
  SrEnv:
    Type: String

Resources:

  InternalPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub smartretail-internal-${SrEnv}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true

  InternalClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub smartretail-internal-client-${SrEnv}
      UserPoolId: !Ref InternalPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
      AccessTokenValidity: 1
      RefreshTokenValidity: 7
      TokenValidityUnits:
        AccessToken: hours
        RefreshToken: days

  SupplierPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub smartretail-supplier-${SrEnv}
      MfaConfiguration: ON

  StoreManagerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: STORE_MANAGER
      UserPoolId: !Ref InternalPool

  ScPlannerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: SC_PLANNER
      UserPoolId: !Ref InternalPool

Outputs:
  InternalPoolId:
    Value: !Ref InternalPool

  InternalClientId:
    Value: !Ref InternalClient